package com.example.sorted.ui.theme
import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF006a68)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFF6ff7f3)
val md_theme_light_onPrimaryContainer = Color(0xFF002020)
val md_theme_light_secondary = Color(0xFF4a6362)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFcce8e6)
val md_theme_light_onSecondaryContainer = Color(0xFF051f1f)
val md_theme_light_tertiary = Color(0xFF4a607b)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFd0e4ff)
val md_theme_light_onTertiaryContainer = Color(0xFF021d35)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfbfdfc)
val md_theme_light_onBackground = Color(0xFF191c1c)
val md_theme_light_surface = Color(0xFFfbfdfc)
val md_theme_light_onSurface = Color(0xFF191c1c)
val md_theme_light_surfaceVariant = Color(0xFFdae4e3)
val md_theme_light_onSurfaceVariant = Color(0xFF3f4948)
val md_theme_light_outline = Color(0xFF6f7978)
val md_theme_light_inverseOnSurface = Color(0xFFeff1f0)
val md_theme_light_inverseSurface = Color(0xFF2e3131)
val md_theme_light_inversePrimary = Color(0xFF4ddad6)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF4ddad6)
val md_theme_dark_onPrimary = Color(0xFF003736)
val md_theme_dark_primaryContainer = Color(0xFF00504e)
val md_theme_dark_onPrimaryContainer = Color(0xFF6ff7f3)
val md_theme_dark_secondary = Color(0xFFb0ccca)
val md_theme_dark_onSecondary = Color(0xFF1b3534)
val md_theme_dark_secondaryContainer = Color(0xFF324b4a)
val md_theme_dark_onSecondaryContainer = Color(0xFFcce8e6)
val md_theme_dark_tertiary = Color(0xFFb2c8e8)
val md_theme_dark_onTertiary = Color(0xFF1b324b)
val md_theme_dark_tertiaryContainer = Color(0xFF324862)
val md_theme_dark_onTertiaryContainer = Color(0xFFd0e4ff)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF191c1c)
val md_theme_dark_onBackground = Color(0xFFe1e3e2)
val md_theme_dark_surface = Color(0xFF191c1c)
val md_theme_dark_onSurface = Color(0xFFe1e3e2)
val md_theme_dark_surfaceVariant = Color(0xFF3f4948)
val md_theme_dark_onSurfaceVariant = Color(0xFFbec8c7)
val md_theme_dark_outline = Color(0xFF889392)
val md_theme_dark_inverseOnSurface = Color(0xFF191c1c)
val md_theme_dark_inverseSurface = Color(0xFFe1e3e2)
val md_theme_dark_inversePrimary = Color(0xFF006a68)
val md_theme_dark_shadow = Color(0xFF000000)



val seed = Color(0xFF79ccc9)
val error = Color(0xFFba1b1b)